#!/bin/bash
# Историческая памятка по experimental reality-xhttp
echo "=== Настройка VLESS+REALITY+XHTTP (experimental) ==="
echo ""
echo "Standalone Xray на VPS:"
echo "  - Протокол: vless"
echo "  - Порт: 2083"
echo "  - Transport: XHTTP (splithttp)"
echo "  - Security: Reality"
echo "  - Dest: cdn.jsdelivr.net:443"
echo "  - SNI: cdn.jsdelivr.net"
echo "  - Flow: ПУСТОЙ (Vision несовместим с XHTTP)"
echo "  - Fingerprint: chrome"
echo ""
echo "Скопируйте Public Key → XRAY_XHTTP_PUBLIC_KEY"
echo "Скопируйте UUID → XRAY_XHTTP_UUID"
